drop table if exists nppes.source;
create table nppes.source (
"NPI" integer,
"Entity Type Code" varchar (1),
"Replacement NPI" varchar (10),
"Employer Identification Number (EIN)" VARCHAR (9),
"Provider Organization Name (Legal Business Name)" VARCHAR (70),
"Provider Last Name (Legal Name)" VARCHAR (35),
"Provider First Name" VARCHAR (20),
"Provider Middle Name" VARCHAR (20),
"Provider Name Prefix Text" VARCHAR (5),
"Provider Name Suffix Text" VARCHAR (5),
"Provider Credential Text" VARCHAR (20),
"Provider Other Organization Name" VARCHAR (70),
"Provider Other Organization Name Type Code" VARCHAR (1),
"Provider Other Last Name" VARCHAR (35),
"Provider Other First Name" VARCHAR (20),
"Provider Other Middle Name" VARCHAR (20),
"Provider Other Name Prefix Text" VARCHAR (5),
"Provider Other Name Suffix Text" VARCHAR (5),
"Provider Other Credential Text" VARCHAR (20),
"Provider Other Last Name Type Code" varchar (1),
"Provider First Line Business Mailing Address" VARCHAR (55),
"Provider Second Line Business Mailing Address" VARCHAR (55),
"Provider Business Mailing Address City Name" VARCHAR (40),
"Provider Business Mailing Address State Name" VARCHAR (40),
"Provider Business Mailing Address Postal Code" VARCHAR (20),
"Provider Business Mailing Address Country Code" VARCHAR (2),
"Provider Business Mailing Address Telephone Number" VARCHAR (20),
"Provider Business Mailing Address Fax Number" VARCHAR (20),
"Provider First Line Business Practice Location Address" VARCHAR (55),
"Provider Second Line Business Practice Location Address" VARCHAR (55),
"Provider Business Practice Location Address City Name" VARCHAR (40),
"Provider Business Practice Location Address State Name" VARCHAR (40),
"Provider Business Practice Location Address Postal Code" VARCHAR (20),
"Provider Business Practice Location Address Country Code" VARCHAR (2),
"Provider Business Practice Location Address Telephone Number" VARCHAR (20),
"Provider Business Practice Location Address Fax Number" VARCHAR (20),
"Provider Enumeration Date" varchar(10),
"Last Update Date" varchar(10),
"NPI Deactivation Reason Code" VARCHAR (2),
"NPI Deactivation Date" varchar(10),
"NPI Reactivation Date" varchar(10),
"Provider Gender Code" VARCHAR (1),
"Authorized Official Last Name" VARCHAR (35),
"Authorized Official First Name" VARCHAR (20),
"Authorized Official Middle Name" VARCHAR (20),
"Authorized Official Title or Position" VARCHAR (35),
"Authorized Official Telephone Number" VARCHAR (20),
"Healthcare Provider Taxonomy Code_1" VARCHAR (10),
"Provider License Number_1" VARCHAR (20),
"Provider License Number State Code_1" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_1" VARCHAR (1),
"Healthcare Provider Taxonomy Code_2" VARCHAR (10),
"Provider License Number_2" VARCHAR (20),
"Provider License Number State Code_2" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_2" VARCHAR (1),
"Healthcare Provider Taxonomy Code_3" VARCHAR (10),
"Provider License Number_3" VARCHAR (20),
"Provider License Number State Code_3" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_3" VARCHAR (1),
"Healthcare Provider Taxonomy Code_4" VARCHAR (10),
"Provider License Number_4" VARCHAR (20),
"Provider License Number State Code_4" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_4" VARCHAR (1),
"Healthcare Provider Taxonomy Code_5" VARCHAR (10),
"Provider License Number_5" VARCHAR (20),
"Provider License Number State Code_5" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_5" VARCHAR (1),
"Healthcare Provider Taxonomy Code_6" VARCHAR (10),
"Provider License Number_6" VARCHAR (20),
"Provider License Number State Code_6" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_6" VARCHAR (1),
"Healthcare Provider Taxonomy Code_7" VARCHAR (10),
"Provider License Number_7" VARCHAR (20),
"Provider License Number State Code_7" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_7" VARCHAR (1),
"Healthcare Provider Taxonomy Code_8" VARCHAR (10),
"Provider License Number_8" VARCHAR (20),
"Provider License Number State Code_8" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_8" VARCHAR (1),
"Healthcare Provider Taxonomy Code_9" VARCHAR (10),
"Provider License Number_9" VARCHAR (20),
"Provider License Number State Code_9" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_9" VARCHAR (1),
"Healthcare Provider Taxonomy Code_10" VARCHAR (10),
"Provider License Number_10" VARCHAR (20),
"Provider License Number State Code_10" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_10" VARCHAR (1),
"Healthcare Provider Taxonomy Code_11" VARCHAR (10),
"Provider License Number_11" VARCHAR (20),
"Provider License Number State Code_11" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_11" VARCHAR (1),
"Healthcare Provider Taxonomy Code_12" VARCHAR (10),
"Provider License Number_12" VARCHAR (20),
"Provider License Number State Code_12" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_12" VARCHAR (1),
"Healthcare Provider Taxonomy Code_13" VARCHAR (10),
"Provider License Number_13" VARCHAR (20),
"Provider License Number State Code_13" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_13" VARCHAR (1),
"Healthcare Provider Taxonomy Code_14" VARCHAR (10),
"Provider License Number_14" VARCHAR (20),
"Provider License Number State Code_14" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_14" VARCHAR (1),
"Healthcare Provider Taxonomy Code_15" VARCHAR (10),
"Provider License Number_15" VARCHAR (20),
"Provider License Number State Code_15" VARCHAR (2),
"Healthcare Provider Primary Taxonomy Switch_15" VARCHAR (1),
"Other Provider Identifier_1" VARCHAR (20),
"Other Provider Identifier Type Code_1" VARCHAR (2),
"Other Provider Identifier State_1" VARCHAR (2),
"Other Provider Identifier Issuer_1" VARCHAR (80),
"Other Provider Identifier_2" VARCHAR (20),
"Other Provider Identifier Type Code_2" VARCHAR (2),
"Other Provider Identifier State_2" VARCHAR (2),
"Other Provider Identifier Issuer_2" VARCHAR (80),
"Other Provider Identifier_3" VARCHAR (20),
"Other Provider Identifier Type Code_3" VARCHAR (2),
"Other Provider Identifier State_3" VARCHAR (2),
"Other Provider Identifier Issuer_3" VARCHAR (80),
"Other Provider Identifier_4" VARCHAR (20),
"Other Provider Identifier Type Code_4" VARCHAR (2),
"Other Provider Identifier State_4" VARCHAR (2),
"Other Provider Identifier Issuer_4" VARCHAR (80),
"Other Provider Identifier_5" VARCHAR (20),
"Other Provider Identifier Type Code_5" VARCHAR (2),
"Other Provider Identifier State_5" VARCHAR (2),
"Other Provider Identifier Issuer_5" VARCHAR (80),
"Other Provider Identifier_6" VARCHAR (20),
"Other Provider Identifier Type Code_6" VARCHAR (2),
"Other Provider Identifier State_6" VARCHAR (2),
"Other Provider Identifier Issuer_6" VARCHAR (80),
"Other Provider Identifier_7" VARCHAR (20),
"Other Provider Identifier Type Code_7" VARCHAR (2),
"Other Provider Identifier State_7" VARCHAR (2),
"Other Provider Identifier Issuer_7" VARCHAR (80),
"Other Provider Identifier_8" VARCHAR (20),
"Other Provider Identifier Type Code_8" VARCHAR (2),
"Other Provider Identifier State_8" VARCHAR (2),
"Other Provider Identifier Issuer_8" VARCHAR (80),
"Other Provider Identifier_9" VARCHAR (20),
"Other Provider Identifier Type Code_9" VARCHAR (2),
"Other Provider Identifier State_9" VARCHAR (2),
"Other Provider Identifier Issuer_9" VARCHAR (80),
"Other Provider Identifier_10" VARCHAR (20),
"Other Provider Identifier Type Code_10" VARCHAR (2),
"Other Provider Identifier State_10" VARCHAR (2),
"Other Provider Identifier Issuer_10" VARCHAR (80),
"Other Provider Identifier_11" VARCHAR (20),
"Other Provider Identifier Type Code_11" VARCHAR (2),
"Other Provider Identifier State_11" VARCHAR (2),
"Other Provider Identifier Issuer_11" VARCHAR (80),
"Other Provider Identifier_12" VARCHAR (20),
"Other Provider Identifier Type Code_12" VARCHAR (2),
"Other Provider Identifier State_12" VARCHAR (2),
"Other Provider Identifier Issuer_12" VARCHAR (80),
"Other Provider Identifier_13" VARCHAR (20),
"Other Provider Identifier Type Code_13" VARCHAR (2),
"Other Provider Identifier State_13" VARCHAR (2),
"Other Provider Identifier Issuer_13" VARCHAR (80),
"Other Provider Identifier_14" VARCHAR (20),
"Other Provider Identifier Type Code_14" VARCHAR (2),
"Other Provider Identifier State_14" VARCHAR (2),
"Other Provider Identifier Issuer_14" VARCHAR (80),
"Other Provider Identifier_15" VARCHAR (20),
"Other Provider Identifier Type Code_15" VARCHAR (2),
"Other Provider Identifier State_15" VARCHAR (2),
"Other Provider Identifier Issuer_15" VARCHAR (80),
"Other Provider Identifier_16" VARCHAR (20),
"Other Provider Identifier Type Code_16" VARCHAR (2),
"Other Provider Identifier State_16" VARCHAR (2),
"Other Provider Identifier Issuer_16" VARCHAR (80),
"Other Provider Identifier_17" VARCHAR (20),
"Other Provider Identifier Type Code_17" VARCHAR (2),
"Other Provider Identifier State_17" VARCHAR (2),
"Other Provider Identifier Issuer_17" VARCHAR (80),
"Other Provider Identifier_18" VARCHAR (20),
"Other Provider Identifier Type Code_18" VARCHAR (2),
"Other Provider Identifier State_18" VARCHAR (2),
"Other Provider Identifier Issuer_18" VARCHAR (80),
"Other Provider Identifier_19" VARCHAR (20),
"Other Provider Identifier Type Code_19" VARCHAR (2),
"Other Provider Identifier State_19" VARCHAR (2),
"Other Provider Identifier Issuer_19" VARCHAR (80),
"Other Provider Identifier_20" VARCHAR (20),
"Other Provider Identifier Type Code_20" VARCHAR (2),
"Other Provider Identifier State_20" VARCHAR (2),
"Other Provider Identifier Issuer_20" VARCHAR (80),
"Other Provider Identifier_21" VARCHAR (20),
"Other Provider Identifier Type Code_21" VARCHAR (2),
"Other Provider Identifier State_21" VARCHAR (2),
"Other Provider Identifier Issuer_21" VARCHAR (80),
"Other Provider Identifier_22" VARCHAR (20),
"Other Provider Identifier Type Code_22" VARCHAR (2),
"Other Provider Identifier State_22" VARCHAR (2),
"Other Provider Identifier Issuer_22" VARCHAR (80),
"Other Provider Identifier_23" VARCHAR (20),
"Other Provider Identifier Type Code_23" VARCHAR (2),
"Other Provider Identifier State_23" VARCHAR (2),
"Other Provider Identifier Issuer_23" VARCHAR (80),
"Other Provider Identifier_24" VARCHAR (20),
"Other Provider Identifier Type Code_24" VARCHAR (2),
"Other Provider Identifier State_24" VARCHAR (2),
"Other Provider Identifier Issuer_24" VARCHAR (80),
"Other Provider Identifier_25" VARCHAR (20),
"Other Provider Identifier Type Code_25" VARCHAR (2),
"Other Provider Identifier State_25" VARCHAR (2),
"Other Provider Identifier Issuer_25" VARCHAR (80),
"Other Provider Identifier_26" VARCHAR (20),
"Other Provider Identifier Type Code_26" VARCHAR (2),
"Other Provider Identifier State_26" VARCHAR (2),
"Other Provider Identifier Issuer_26" VARCHAR (80),
"Other Provider Identifier_27" VARCHAR (20),
"Other Provider Identifier Type Code_27" VARCHAR (2),
"Other Provider Identifier State_27" VARCHAR (2),
"Other Provider Identifier Issuer_27" VARCHAR (80),
"Other Provider Identifier_28" VARCHAR (20),
"Other Provider Identifier Type Code_28" VARCHAR (2),
"Other Provider Identifier State_28" VARCHAR (2),
"Other Provider Identifier Issuer_28" VARCHAR (80),
"Other Provider Identifier_29" VARCHAR (20),
"Other Provider Identifier Type Code_29" VARCHAR (2),
"Other Provider Identifier State_29" VARCHAR (2),
"Other Provider Identifier Issuer_29" VARCHAR (80),
"Other Provider Identifier_30" VARCHAR (20),
"Other Provider Identifier Type Code_30" VARCHAR (2),
"Other Provider Identifier State_30" VARCHAR (2),
"Other Provider Identifier Issuer_30" VARCHAR (80),
"Other Provider Identifier_31" VARCHAR (20),
"Other Provider Identifier Type Code_31" VARCHAR (2),
"Other Provider Identifier State_31" VARCHAR (2),
"Other Provider Identifier Issuer_31" VARCHAR (80),
"Other Provider Identifier_32" VARCHAR (20),
"Other Provider Identifier Type Code_32" VARCHAR (2),
"Other Provider Identifier State_32" VARCHAR (2),
"Other Provider Identifier Issuer_32" VARCHAR (80),
"Other Provider Identifier_33" VARCHAR (20),
"Other Provider Identifier Type Code_33" VARCHAR (2),
"Other Provider Identifier State_33" VARCHAR (2),
"Other Provider Identifier Issuer_33" VARCHAR (80),
"Other Provider Identifier_34" VARCHAR (20),
"Other Provider Identifier Type Code_34" VARCHAR (2),
"Other Provider Identifier State_34" VARCHAR (2),
"Other Provider Identifier Issuer_34" VARCHAR (80),
"Other Provider Identifier_35" VARCHAR (20),
"Other Provider Identifier Type Code_35" VARCHAR (2),
"Other Provider Identifier State_35" VARCHAR (2),
"Other Provider Identifier Issuer_35" VARCHAR (80),
"Other Provider Identifier_36" VARCHAR (20),
"Other Provider Identifier Type Code_36" VARCHAR (2),
"Other Provider Identifier State_36" VARCHAR (2),
"Other Provider Identifier Issuer_36" VARCHAR (80),
"Other Provider Identifier_37" VARCHAR (20),
"Other Provider Identifier Type Code_37" VARCHAR (2),
"Other Provider Identifier State_37" VARCHAR (2),
"Other Provider Identifier Issuer_37" VARCHAR (80),
"Other Provider Identifier_38" VARCHAR (20),
"Other Provider Identifier Type Code_38" VARCHAR (2),
"Other Provider Identifier State_38" VARCHAR (2),
"Other Provider Identifier Issuer_38" VARCHAR (80),
"Other Provider Identifier_39" VARCHAR (20),
"Other Provider Identifier Type Code_39" VARCHAR (2),
"Other Provider Identifier State_39" VARCHAR (2),
"Other Provider Identifier Issuer_39" VARCHAR (80),
"Other Provider Identifier_40" VARCHAR (20),
"Other Provider Identifier Type Code_40" VARCHAR (2),
"Other Provider Identifier State_40" VARCHAR (2),
"Other Provider Identifier Issuer_40" VARCHAR (80),
"Other Provider Identifier_41" VARCHAR (20),
"Other Provider Identifier Type Code_41" VARCHAR (2),
"Other Provider Identifier State_41" VARCHAR (2),
"Other Provider Identifier Issuer_41" VARCHAR (80),
"Other Provider Identifier_42" VARCHAR (20),
"Other Provider Identifier Type Code_42" VARCHAR (2),
"Other Provider Identifier State_42" VARCHAR (2),
"Other Provider Identifier Issuer_42" VARCHAR (80),
"Other Provider Identifier_43" VARCHAR (20),
"Other Provider Identifier Type Code_43" VARCHAR (2),
"Other Provider Identifier State_43" VARCHAR (2),
"Other Provider Identifier Issuer_43" VARCHAR (80),
"Other Provider Identifier_44" VARCHAR (20),
"Other Provider Identifier Type Code_44" VARCHAR (2),
"Other Provider Identifier State_44" VARCHAR (2),
"Other Provider Identifier Issuer_44" VARCHAR (80),
"Other Provider Identifier_45" VARCHAR (20),
"Other Provider Identifier Type Code_45" VARCHAR (2),
"Other Provider Identifier State_45" VARCHAR (2),
"Other Provider Identifier Issuer_45" VARCHAR (80),
"Other Provider Identifier_46" VARCHAR (20),
"Other Provider Identifier Type Code_46" VARCHAR (2),
"Other Provider Identifier State_46" VARCHAR (2),
"Other Provider Identifier Issuer_46" VARCHAR (80),
"Other Provider Identifier_47" VARCHAR (20),
"Other Provider Identifier Type Code_47" VARCHAR (2),
"Other Provider Identifier State_47" VARCHAR (2),
"Other Provider Identifier Issuer_47" VARCHAR (80),
"Other Provider Identifier_48" VARCHAR (20),
"Other Provider Identifier Type Code_48" VARCHAR (2),
"Other Provider Identifier State_48" VARCHAR (2),
"Other Provider Identifier Issuer_48" VARCHAR (80),
"Other Provider Identifier_49" VARCHAR (20),
"Other Provider Identifier Type Code_49" VARCHAR (2),
"Other Provider Identifier State_49" VARCHAR (2),
"Other Provider Identifier Issuer_49" VARCHAR (80),
"Other Provider Identifier_50" VARCHAR (20),
"Other Provider Identifier Type Code_50" VARCHAR (2),
"Other Provider Identifier State_50" VARCHAR (2),
"Other Provider Identifier Issuer_50" VARCHAR (80),
"Is Sole Proprietor" VARCHAR (1),
"Is Organization Subpart" VARCHAR (1),
"Parent Organization LBN" VARCHAR (70),
"Parent Organization TIN" VARCHAR (9),
"Authorized Official Name Prefix Text" VARCHAR (5),
"Authorized Official Name Suffix Text" VARCHAR (5),
"Authorized Official Credential Text" VARCHAR (20),
"Healthcare Provider Taxonomy Group_1" VARCHAR (70),
"Healthcare Provider Taxonomy Group_2" VARCHAR (70),
"Healthcare Provider Taxonomy Group_3" VARCHAR (70),
"Healthcare Provider Taxonomy Group_4" VARCHAR (70),
"Healthcare Provider Taxonomy Group_5" VARCHAR (70),
"Healthcare Provider Taxonomy Group_6" VARCHAR (70),
"Healthcare Provider Taxonomy Group_7" VARCHAR (70),
"Healthcare Provider Taxonomy Group_8" VARCHAR (70),
"Healthcare Provider Taxonomy Group_9" VARCHAR (70),
"Healthcare Provider Taxonomy Group_10" VARCHAR (70),
"Healthcare Provider Taxonomy Group_11" VARCHAR (70),
"Healthcare Provider Taxonomy Group_12" VARCHAR (70),
"Healthcare Provider Taxonomy Group_13" VARCHAR (70),
"Healthcare Provider Taxonomy Group_14" VARCHAR (70),
"Healthcare Provider Taxonomy Group_15" VARCHAR (70)
);

copy nppes.source from 'C:\npidata.csv' with 
(
format csv, 
header true
);

ALTER TABLE nppes.source
    ADD PRIMARY KEY ("NPI");

 -- needs to be a better way for this
-- update nppes.source set "Healthcare Provider Taxonomy Code_1" = NULL where "Healthcare Provider Taxonomy Code_1" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_2" = NULL where "Healthcare Provider Taxonomy Code_2" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_3" = NULL where "Healthcare Provider Taxonomy Code_3" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_4" = NULL where "Healthcare Provider Taxonomy Code_4" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_5" = NULL where "Healthcare Provider Taxonomy Code_5" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_6" = NULL where "Healthcare Provider Taxonomy Code_6" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_7" = NULL where "Healthcare Provider Taxonomy Code_7" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_8" = NULL where "Healthcare Provider Taxonomy Code_8" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_9" = NULL where "Healthcare Provider Taxonomy Code_9" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_10" = NULL where "Healthcare Provider Taxonomy Code_10" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_11" = NULL where "Healthcare Provider Taxonomy Code_11" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_12" = NULL where "Healthcare Provider Taxonomy Code_12" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_13" = NULL where "Healthcare Provider Taxonomy Code_13" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_14" = NULL where "Healthcare Provider Taxonomy Code_14" = '';
-- update nppes.source set "Healthcare Provider Taxonomy Code_15" = NULL where "Healthcare Provider Taxonomy Code_15" = '';