create table nppes.otheridtest (
"NPI" integer NOT NULL,
"Other Provider Identifier" varchar(20) NOT NULL,
"Other Provider Identifier Type Code" varchar(2),
"Other Provider Identifier State" varchar(2),
"Other Provider Identifier Issuer" varchar(80)
);
-- insert into nppes.otherid 
-- select 
-- "NPI",
-- "Other Provider Identifier_1",
-- "Other Provider Identifier Type Code_1",
-- "Other Provider Identifier State_1",
-- "Other Provider Identifier Issuer_1"
-- from nppes.source
-- where "Other Provider Identifier_1" != '';
-- 
-- insert into nppes.otherid 
-- select 
-- "NPI",
-- "Other Provider Identifier_4",
-- "Other Provider Identifier Type Code_4",
-- "Other Provider Identifier State_4",
-- "Other Provider Identifier Issuer_4"
-- from nppes.source
-- where "Other Provider Identifier_4" != '';
insert into nppes.otheridtest 
select 
"NPI",
unnest(ARRAY[
"Other Provider Identifier_1",
"Other Provider Identifier_2",
"Other Provider Identifier_3",
"Other Provider Identifier_4",
"Other Provider Identifier_5",
"Other Provider Identifier_6",
"Other Provider Identifier_7",
"Other Provider Identifier_8",
"Other Provider Identifier_9",
"Other Provider Identifier_10",
"Other Provider Identifier_11",
"Other Provider Identifier_12",
"Other Provider Identifier_13",
"Other Provider Identifier_14",
"Other Provider Identifier_15",
"Other Provider Identifier_16",
"Other Provider Identifier_17",
"Other Provider Identifier_18",
"Other Provider Identifier_19",
"Other Provider Identifier_20",
"Other Provider Identifier_21",
"Other Provider Identifier_22",
"Other Provider Identifier_23",
"Other Provider Identifier_24",
"Other Provider Identifier_25",
"Other Provider Identifier_26",
"Other Provider Identifier_27",
"Other Provider Identifier_28",
"Other Provider Identifier_29",
"Other Provider Identifier_30",
"Other Provider Identifier_31",
"Other Provider Identifier_32",
"Other Provider Identifier_33",
"Other Provider Identifier_34",
"Other Provider Identifier_35",
"Other Provider Identifier_36",
"Other Provider Identifier_37",
"Other Provider Identifier_38",
"Other Provider Identifier_39",
"Other Provider Identifier_40",
"Other Provider Identifier_41",
"Other Provider Identifier_42",
"Other Provider Identifier_43",
"Other Provider Identifier_44",
"Other Provider Identifier_45",
"Other Provider Identifier_46",
"Other Provider Identifier_47",
"Other Provider Identifier_48",
"Other Provider Identifier_49",
"Other Provider Identifier_50"]) 
as "Other Provider Identifier",
unnest(ARRAY[
"Other Provider Identifier Type Code_1",
"Other Provider Identifier Type Code_2",
"Other Provider Identifier Type Code_3",
"Other Provider Identifier Type Code_4",
"Other Provider Identifier Type Code_5",
"Other Provider Identifier Type Code_6",
"Other Provider Identifier Type Code_7",
"Other Provider Identifier Type Code_8",
"Other Provider Identifier Type Code_9",
"Other Provider Identifier Type Code_10",
"Other Provider Identifier Type Code_11",
"Other Provider Identifier Type Code_12",
"Other Provider Identifier Type Code_13",
"Other Provider Identifier Type Code_14",
"Other Provider Identifier Type Code_15",
"Other Provider Identifier Type Code_16",
"Other Provider Identifier Type Code_17",
"Other Provider Identifier Type Code_18",
"Other Provider Identifier Type Code_19",
"Other Provider Identifier Type Code_20",
"Other Provider Identifier Type Code_21",
"Other Provider Identifier Type Code_22",
"Other Provider Identifier Type Code_23",
"Other Provider Identifier Type Code_24",
"Other Provider Identifier Type Code_25",
"Other Provider Identifier Type Code_26",
"Other Provider Identifier Type Code_27",
"Other Provider Identifier Type Code_28",
"Other Provider Identifier Type Code_29",
"Other Provider Identifier Type Code_30",
"Other Provider Identifier Type Code_31",
"Other Provider Identifier Type Code_32",
"Other Provider Identifier Type Code_33",
"Other Provider Identifier Type Code_34",
"Other Provider Identifier Type Code_35",
"Other Provider Identifier Type Code_36",
"Other Provider Identifier Type Code_37",
"Other Provider Identifier Type Code_38",
"Other Provider Identifier Type Code_39",
"Other Provider Identifier Type Code_40",
"Other Provider Identifier Type Code_41",
"Other Provider Identifier Type Code_42",
"Other Provider Identifier Type Code_43",
"Other Provider Identifier Type Code_44",
"Other Provider Identifier Type Code_45",
"Other Provider Identifier Type Code_46",
"Other Provider Identifier Type Code_47",
"Other Provider Identifier Type Code_48",
"Other Provider Identifier Type Code_49",
"Other Provider Identifier Type Code_50"]) 
as "Other Provider Identifier Type Code",
unnest(ARRAY[
"Other Provider Identifier State_1",
"Other Provider Identifier State_2",
"Other Provider Identifier State_3",
"Other Provider Identifier State_4",
"Other Provider Identifier State_5",
"Other Provider Identifier State_6",
"Other Provider Identifier State_7",
"Other Provider Identifier State_8",
"Other Provider Identifier State_9",
"Other Provider Identifier State_10",
"Other Provider Identifier State_11",
"Other Provider Identifier State_12",
"Other Provider Identifier State_13",
"Other Provider Identifier State_14",
"Other Provider Identifier State_15",
"Other Provider Identifier State_16",
"Other Provider Identifier State_17",
"Other Provider Identifier State_18",
"Other Provider Identifier State_19",
"Other Provider Identifier State_20",
"Other Provider Identifier State_21",
"Other Provider Identifier State_22",
"Other Provider Identifier State_23",
"Other Provider Identifier State_24",
"Other Provider Identifier State_25",
"Other Provider Identifier State_26",
"Other Provider Identifier State_27",
"Other Provider Identifier State_28",
"Other Provider Identifier State_29",
"Other Provider Identifier State_30",
"Other Provider Identifier State_31",
"Other Provider Identifier State_32",
"Other Provider Identifier State_33",
"Other Provider Identifier State_34",
"Other Provider Identifier State_35",
"Other Provider Identifier State_36",
"Other Provider Identifier State_37",
"Other Provider Identifier State_38",
"Other Provider Identifier State_39",
"Other Provider Identifier State_40",
"Other Provider Identifier State_41",
"Other Provider Identifier State_42",
"Other Provider Identifier State_43",
"Other Provider Identifier State_44",
"Other Provider Identifier State_45",
"Other Provider Identifier State_46",
"Other Provider Identifier State_47",
"Other Provider Identifier State_48",
"Other Provider Identifier State_49",
"Other Provider Identifier State_50"]) 
as "Other Provider Identifier State",
unnest(ARRAY[
"Other Provider Identifier Issuer_1",
"Other Provider Identifier Issuer_2",
"Other Provider Identifier Issuer_3",
"Other Provider Identifier Issuer_4",
"Other Provider Identifier Issuer_5",
"Other Provider Identifier Issuer_6",
"Other Provider Identifier Issuer_7",
"Other Provider Identifier Issuer_8",
"Other Provider Identifier Issuer_9",
"Other Provider Identifier Issuer_10",
"Other Provider Identifier Issuer_11",
"Other Provider Identifier Issuer_12",
"Other Provider Identifier Issuer_13",
"Other Provider Identifier Issuer_14",
"Other Provider Identifier Issuer_15",
"Other Provider Identifier Issuer_16",
"Other Provider Identifier Issuer_17",
"Other Provider Identifier Issuer_18",
"Other Provider Identifier Issuer_19",
"Other Provider Identifier Issuer_20",
"Other Provider Identifier Issuer_21",
"Other Provider Identifier Issuer_22",
"Other Provider Identifier Issuer_23",
"Other Provider Identifier Issuer_24",
"Other Provider Identifier Issuer_25",
"Other Provider Identifier Issuer_26",
"Other Provider Identifier Issuer_27",
"Other Provider Identifier Issuer_28",
"Other Provider Identifier Issuer_29",
"Other Provider Identifier Issuer_30",
"Other Provider Identifier Issuer_31",
"Other Provider Identifier Issuer_32",
"Other Provider Identifier Issuer_33",
"Other Provider Identifier Issuer_34",
"Other Provider Identifier Issuer_35",
"Other Provider Identifier Issuer_36",
"Other Provider Identifier Issuer_37",
"Other Provider Identifier Issuer_38",
"Other Provider Identifier Issuer_39",
"Other Provider Identifier Issuer_40",
"Other Provider Identifier Issuer_41",
"Other Provider Identifier Issuer_42",
"Other Provider Identifier Issuer_43",
"Other Provider Identifier Issuer_44",
"Other Provider Identifier Issuer_45",
"Other Provider Identifier Issuer_46",
"Other Provider Identifier Issuer_47",
"Other Provider Identifier Issuer_48",
"Other Provider Identifier Issuer_49",
"Other Provider Identifier Issuer_50"]) 
as "Other Provider Identifier Issuer"
from nppes.source
order by "NPI" limit 100